### ISSUE TITLE
input variable is undefined

### ISSUE THREAD

**Issue by suleymanccelik** [cbalit/html5-paper-input#2]
Demo of your component page is working but in my application input variable in html5-paper-input element is undefined. So validation process is not working. In my application I install your component with bower. 

I miss something but I can't find. Can you help me?

**Comment by cbalit** [comment]
can you post a piece of code where is not working ?

**Comment by suleymanccelik** [comment]
validateAttributes: function() { this.input.setAttribute('type', this.type); } 

error message is "Cannot read property 'setAttribute' of undefined"

I initialize input variable following code : this.input = this.decorator.childNodes[1];  -> In this way html5-paper-input is working correctly.

**Comment by cbalit** [comment]
Ok i see. It is because i'm extending paper-input element and I retrieve the input using the id. It's work with paper-input master  but not on previous release because the input has no id. So I fix the v1.0.1 so that it retrieve the input even if there is no id. Just update your compnent and it should work.

**Comment by suleymanccelik** [comment]
Thanks @cbalit

**Comment by cbalit** [comment]
You're welcome. If you like it don't hesitate to add a star....
